spring:
  mail:
    to: 邮件接收方（逗号分割）
    host: smtp.163.com
    port: 465
    username: 用户名
    password: 密码或授权码
    default-encoding: utf-8
    protocol: smtp
    properties:
#      mail.debug: true
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
      mail.smtp.ssl.required: true