#spring:
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    druid:
#      mes:
#        url: jdbc:sqlserver://192.168.50.103:1433;DatabaseName=Runtime
#        username: wwUser
#        password: wwUser
#        driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#      ipes:
#        url: jdbc:oracle:thin:@//172.11.6.14:1521/omdb.dlsteel.com
#        username: IMES_PES
#        password: dlpes
#        driver-class-name: oracle.jdbc.OracleDriver
#mybatis:
#  mapper-locations:
#    - mapper/**/**.xml # mapper路径设置
#pagehelper:
#  #  helperDialect: mysql
#  reasonable: false
#  supportMethodsArguments: true
#  params: count=countSql
#  auto-dialect: true  # 默认false,当为true时，自动检验适合的数据库
#  auto-runtime-dialect: true # 这个一定要加上，不然mysql和oracle分页两个只能用一个，另一个会报错，加上后，两中数据库分页都可以用了